# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
#condense_wildcard_suffixes = true
edition = "2018"
#enum_discrim_align_threshold = 20
#fn_args_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
max_width = 80,
merge_imports = true,
newline_style = "Unix",
#struct_field_align_threshold = 20
tab_spaces = 3
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two",
#wrap_comments = true